Repository DavidVidaMi/Sadhana, pull requests merged in 2023-03, with the labels that each got.

#6 Creada Estructura basica con GameManager y la ClasePadre Instrumento
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/GameManager.cs
  Assets/Scripts/GameManager.cs.meta
  Assets/Scripts/Instrumento.cs
  Assets/Scripts/Instrumento.cs.meta
  Assets/Sounds.meta
  Assets/Sprites.meta
  UserSettings/Layouts/default-2021.dwlt
Labels: feature

#10 Creado el funcionamiento basico del juego
  .vscode/settings.json
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Batuta.cs
  Assets/Scripts/Batuta.cs.meta
  Assets/Sprites/250px-Wind_Waker.png
  Assets/Sprites/250px-Wind_Waker.png.meta
  Assets/Sprites/250px-Wind_Waker_espejo.png
  Assets/Sprites/250px-Wind_Waker_espejo.png.meta
Labels: feature

#11 Refactorizacion Instrumento y GameManager
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/EjemploInstrumento.cs
  Assets/Scripts/EjemploInstrumento.cs.meta
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Instrumento.cs
Labels: bugfix, refactor

#12 Feature/instrumentos
  Assets/Prefabs/Bajo.prefab
  Assets/Prefabs/Bajo.prefab.meta
  Assets/Prefabs/Bateria.prefab
  Assets/Prefabs/Bateria.prefab.meta
  Assets/Prefabs/Guitarra.prefab
  Assets/Prefabs/Guitarra.prefab.meta
  Assets/Prefabs/Saxofon.prefab
  Assets/Prefabs/Saxofon.prefab.meta
  Assets/Prefabs/Trompeta.prefab
  Assets/Prefabs/Trompeta.prefab.meta
  Assets/Prefabs/Voz.prefab
  Assets/Prefabs/Voz.prefab.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Bajo.cs
  Assets/Scripts/Bajo.cs.meta
  Assets/Scripts/Bateria.cs
  Assets/Scripts/Bateria.cs.meta
  Assets/Scripts/Guitarra.cs
  Assets/Scripts/Guitarra.cs.meta
  Assets/Scripts/Saxofon.cs
  Assets/Scripts/Saxofon.cs.meta
  Assets/Scripts/Trompeta.cs
  Assets/Scripts/Trompeta.cs.meta
  Assets/Scripts/Voz.cs
  Assets/Scripts/Voz.cs.meta
  UserSettings/Layouts/default-2021.dwlt
Labels: feature

#13 GDD completo, con Extras incluidos
  GDD/1_Introducción/Introduccion.md
  GDD/2_Descripción/Descripcion.md
  GDD/3_Género_y_Características/Genero_y_Caracteristicas.md
  GDD/4_Mecánicas/Mecanicas.md
  GDD/5_A_Futuro/Extras_A_Futuro.md
Labels: documentation

#15 Creado menu y script para pausar juego
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Batuta.cs
  Assets/Scripts/GameManager.cs
  Assets/Scripts/MenuPausa.cs
  Assets/Scripts/MenuPausa.cs.meta
  Assets/Sprites/250px-Wind_Waker_espejo.png.meta
Labels: feature
